### ISSUE TITLE
coolstore ui not reachable after apply knative-serving-service

### ISSUE THREAD

**Issue by lucalann** [RedHat-Middleware-Workshops/cloud-native-workshop-v2-labs-solutions#1]
Hi,
we deployed last version (ocp-4.2) of cloud-native-workshop-v2-infra in a ocp 4.2.0 cluster. 
Then we deployed the labs solutions. 
All seems to work fine (also the serverless scaling pod), but after appling knative-serving-service.yaml, the new created route http://payment.user0-cloudnativeapps.apps.openshift4.xxx.com make the coolstore ui route unavailable.
Could you help us to resolve the issue?
Thanks in advance, regards
Luca

**Comment by danieloh30** [comment]
CCN dev track is currently tested in OCP 4.1 and I'm converting to 4.2. You need to run it in OCP 4.1 at this moment.
